# Generated by Django 6.0.3 on 2026-03-28 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_payment_plan_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usercompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
