# Generated by Codex on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_usercompany_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCompanyAttachment",
        ),
    ]
