# Generated by Django 6.0.3 on 2026-03-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productattachment',
            options={'ordering': ['-created_at']},
        ),
    ]
