# Generated by Codex on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductAttachment",
        ),
    ]
