# Generated by Django 6.0.3 on 2026-03-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='branchattachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='companyattachment',
            options={'ordering': ['-created_at']},
        ),
    ]
