# Generated by Django 6.0.3 on 2026-03-30 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercompany_user'),
        ('organizations', '0002_alter_branch_options_alter_branchattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.usercompany'),
            preserve_default=False,
        ),
    ]
