# Generated by Django 6.0.3 on 2026-03-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_company_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='attachment',
        ),
    ]
