# Generated by Codex on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_remove_branch_attachment_remove_company_attachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BranchAttachment",
        ),
        migrations.DeleteModel(
            name="CompanyAttachment",
        ),
    ]
