# Generated by Django 6.0.3 on 2026-04-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usercompanyattachment'),
        ('organizations', '0005_remove_legacy_attachment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.company'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company'], name='organizatio_company_6ff143_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['name'], name='organizatio_name_594def_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user_company'], name='organizatio_user_co_791e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='organizatio_name_190560_idx'),
        ),
    ]
