# Generated by Django 6.0.3 on 2026-03-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientattachments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientidentifier',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
    ]
