# Generated by Django 6.0.3 on 2026-03-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_client_options_alter_clientattachments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientattachments',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='people.client'),
        ),
        migrations.AlterField(
            model_name='clientidentifier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='people.client'),
        ),
    ]
