# Generated by Codex on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_employeeattachment_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientAttachments",
        ),
        migrations.DeleteModel(
            name="EmployeeAttachment",
        ),
    ]
