# Generated by Django 6.0.3 on 2026-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aijob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='integration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='legaltask',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='company',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
    ]
