# Generated by Django 6.0.3 on 2026-03-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contractclause',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recurringlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recurringprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-created_at']},
        ),
    ]
