# Generated by Codex on 2026-04-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import files.models


def migrate_company_links_to_generic_files(apps, schema_editor):
    File = apps.get_model("files", "File")
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        company_content_type = ContentType.objects.get(
            app_label="organizations",
            model="company",
        )
    except ContentType.DoesNotExist:
        return

    for file in File.objects.exclude(company_id=None):
        file.content_type_id = company_content_type.id
        file.object_id = file.company_id
        file.save(update_fields=["content_type", "object_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_company_user_company"),
        ("files", "0002_alter_file_options"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="object_id",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            migrate_company_links_to_generic_files,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=files.models.upload_to),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="file",
            name="company",
        ),
        migrations.AlterField(
            model_name="file",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="object_id",
            field=models.UUIDField(),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["content_type", "object_id"], name="files_file_content_00f9c1_idx"),
        ),
    ]
