# Generated by Django 5.2.8 on 2026-04-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_unify_generic_file_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='files_file_content_20a48a_idx',
            old_name='files_file_content_00f9c1_idx',
        ),
    ]
